name: update Redmine issue 
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: thaim/redmine-integration-action@main
        with:
          redmine_host: ${{ secrets.REDMINE_HOST }}
          redmine_apikey: ${{ secrets.REDMINE_API_KEY}}
